[project]
name = "digitalengn-monorepo"
version = "1.0.0"
description = "DigitalEngn Monorepo top-level BDD tests"
requires-python = ">=3.12"
dependencies = [
    "behave",
    "requests>=2.32.5",
    "engn",
]

[tool.uv.workspace]
members = ["engn"]

[tool.uv.sources]
engn = { workspace = true }


[project.scripts]
launch = "launch:main"
shutdown = "shutdown:main"
clean = "clean:main"
build = "build:main"
rebuild = "rebuild:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-dir]
"" = "src"

[tool.uv]
package = true
dev-dependencies = [
    "pytest",
    "ruff",
    "pyright",
    "behave",
]
